### ISSUE TITLE
EZ Wifi Broadcast with Navio2? Would love to hear if anyone has accomplished this.

### ISSUE THREAD

**Issue by Mysnomer0** [emlid/pi-gen-navio#3]
Has anyone been able to manually install EZ Wifi Broadcast onto Emlid's Navio2 image? I've been struggling researching this. The Navio2 image now no longer comes with the original WBC, so I was wondering if anyone has been able to combine EZ WBC with the Navio 2 image. This would be an amazing digital HD transmission and autonomous flight system in one. Any help or pointers in a good direction is greatly appreciated.

Thanks,

Mysnomer

**Comment by lucasgrelaud** [comment]
Hi @Mysnomer0 !
EZ WifiBroadcast seems to not be maintaned anymore, so you might try to look for the Open.HD fork.

~~I'm currently working on integrating Open.HD and the Navio2 stack on a Raspbian buster image.
Hopefully i'll finish the it by the end of this week, so have a look :)~~

Repository : [pi-gen-drone](https://github.com/lucasgrelaud/pi-gen-drone/tree/develop)

EDIT : well it might not use Open.HD because of few limitation of the software (telem over tty only especially), but i'll still try to acheive a similar result (telem + RC input + video  over wifi)

**Comment by Mysnomer0** [comment]
Hi Lucas,

I've actually already achieved Navio2 with Wifibroadcast using svpcoms wifibroadcast back in January, and have written a guide on how to do it and contributed it to svpcoms wiki. Glad to see you want to do something similar!

Thanks,

Milan

**Comment by lucasgrelaud** [comment]
ho !
I'll definitly have a look to it!

**Comment by Mysnomer0** [comment]
Here's the link:

https://github.com/svpcom/wifibroadcast/wiki/Navio2-Setup
